### PR TITLE
Bump upper bound on base to support GHC 8.10.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Also regenerated the .travis.yml to support new 8.8 and 8.10 CI targets.

I added a number of intermediate versions of GHC rather than just the latest version for each major version. It seemed like that's how it was configured before hand. It might make more sense to just support 
the most up to date version for each major version.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Any chance of getting this merged and pushed to Hackage @wrengr ?

**Comment by tmcgilchrist** [comment]
Bump!

**Comment by gbaz** [comment]
revision published

**Comment by wrengr** [comment]
Closed by c41b2cc (sorry for the long delay)

**Pull request closed without merging**
