### PR TITLE
Bump dependency bounds for GHC 8.8

### PR DESCRIPTION
**Pull request by bubba**

### CODE REVIEW

**Comment by bubba** [comment]
cc @alanz

**Comment by phadej** [comment]
ping @wrengr

**Comment by tmcgilchrist** [comment]
Also have a dependency on this, could we please get a new version up on hackage?
Happy to do the maintenance stuff if you don't have time.

**Comment by phadej** [comment]
I made revision as requested on hackage trustees [issue tracker](https://github.com/haskell-infra/hackage-trustees/issues/244): https://hackage.haskell.org/package/bytestring-trie-0.2.5.0/revisions/

**Comment by tmcgilchrist** [comment]
Added a PR to bump version bounds for 8.10 here https://github.com/wrengr/bytestring-trie/pull/11

**Comment by wrengr** [comment]
Closed by c41b2cc

**Pull request closed without merging**
